import React,{useEffect} from 'react'
import './CommonContainer.css';
import Header from '../Component/Header/Header';

import Footer from '../Component/Footer/Footer';



const Privacy = () => {


    return(
        <>
        <Header />
        <div className="container-fluid">
        <div className="row">
       
        <p class="ter">

<strong>PRIVACY POLICY</strong>-<a href="#">www.cityonnet.com</a><br/><br/>

<strong>1.	Background</strong><br/><br/>

<strong>1.1.</strong>	This document is an electronic record in terms of (i) Information Technology Act, 2000; (ii) the rules framed there under as applicable; and (iii) the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.<br/><br/>

<strong>1.2.</strong>	This Privacy Policy ("<strong>PrivacyPolicy</strong>") is published in accordance with: (i) Section 43A of the Information Technology Act, 2000; (ii) Regulation 4 of the Information Technology (Reasonable security practices and procedures and sensitive personal information) Rules, 2011 (<strong>"SPI Rules"</strong>); and (iii) Regulation 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, that require publishing the privacy policy that is applicable in relation to the access or usage of  www.cityonnet.com (<strong>"Website"</strong>).<br/><br/>

<strong>1.3.</strong>	This Privacy Policy covers: (i) the type of information collected from the Users of the Website including sensitive personal data or information; (ii) the purpose, means and modes of usage of such information; and (iii) how and to whom such information which has been collected will be disclosed.<br/><br/>

<strong>1.4.</strong>	For the purpose of this Privacy Policy, wherever the context so requires <strong>"You"</strong>,<strong> "Your"</strong> or <strong>"User"</strong> shall mean any natural or legal person who uses the Website for availing services offered by the Website. The terms <strong>"We"</strong>, <strong>"Us"</strong>, <strong>"Our"</strong> shall mean <strong>"Cityonthenet&#8482"</strong>.<br/><br/>

<strong>1.5.</strong>	We reserve the right to make changes to this Privacy Policy at any time. We will provide notice of any significant changes through the Website, or by other means so that you may review the changes before you continue to use the Website. Any such modifications will become effective immediately upon posting to the Website and your continued use of the Website, and/or the Services constitutes your agreement to such modifications. If you object to any changes, you may close your account. You agree to periodically review the current version of the Privacy Policy as posted on the Website.<br/><br/>

<strong>2.	Type of information collected from the User</strong><br/><br/>

<strong>2.1.</strong>	For the purpose of this Privacy Policy, <strong>"personal information"</strong> as defined under Section 2(i) of the SPI Rules means, any information that relates to a natural person, which, either directly or indirectly, in combination with other information available or likely to be available with a body corporate, is capable of identifying such person.<br/><br/>

<strong>2.2.</strong>	"<strong>Sensitive personal Information"</strong> as defined under Section 3 of the SPI Rules means such personal information which consists of information relating to:<br/></p>

<p class="spa">(i)	Password;<br/><br/>

(ii)	financial information such as Bank account or credit card or debit card or other payment instrument details;<br/><br/>

(iii)	physical, physiological and mental health condition;<br/><br/>

(iv)	Sexual orientation;<br/><br/>

(v)	Medical records and history;<br/><br/>

(vi)	Biometric information;<br/><br/>

(vii)	Any details relating to the above clauses as provided to the body corporate for providing service; and<br/><br/>

(viii)	Any of the information received under above clauses by a body corporate for processing, stored or processed under lawful contract or otherwise.<br/><br/></p>


<p class="ter"><strong>2.3.</strong>	If you choose to use the Websiteto purchase products that are marketed by the retailer on the Website, You will be required to provide us with the following information while:<br/></p>

<p class="spa">(i)	Name of the User<br/><br/>

(ii)	E-mail address of the User<br/><br/>

(iii)	Residential address/Official address<br/><br/>

(iv)	Phone Number of the User<br/><br/></p>

<p class="ter"><strong>3.	How the collected information will be used</strong><br/><br/>

<strong>3.1.</strong>	Sensitive Personal Information and other information collected under Clause 2.3 will be used in the manner described below:<br/></p>

<p class="spa">(i)	Name: The User name shall be used to processYour order and personalize all communication that are sent to the User by us.<br/><br/>

(ii)	E-mail Address: Your e-mail address shall be used to communicate:<br/></p>

<p class="spa1">(a)	The confirmation of your order.<br/>

(b)	Any online or offline offers based on your previous orders and interest.<br/><br/></p>

<p class="spa">(iii)	Phone Number: The phone number will be an alternative method to contact the User, should there be any cancellation/interruption or for any other matter related to the services to be availed by the User through the Website.<br/><br/>

(iv)	Credit Card/Debit Card/Demand Draft information: Credit card/Debit Card/Demand draft is used for charging the User for purchasing the products from the retailer<br/><br/></p>

<p class="ter"><strong>3.2.</strong>	We use personal information to provide the services you request. To the extent we use your personal information to market to you, we will provide you the ability to opt-out of such uses. We use your personal information to resolve disputes; troubleshoot problems; help promote a safe service; collect money; measure consumer interest in our products and services, inform you about online and offline offers, products, services, and updates; customize your experience; detect and protect us against error, fraud and other criminal activity; enforce our terms and conditions; and as otherwise described to you at the time of collection.<br/><br/>
With your consent, we will have access to your SMS, contacts in your directory, call history, location and device information and we may request you to provide your PAN to check your eligibility for certain products/services including but not limited to providing credit) being offered by us, our affiliates or our lending partners. We may share this data with our affiliates / sellers or our lending partners for the same purposes as mentioned above, however, we will not store any Aadhaar data ourselves. In the event that consent to this such use of data is withdrawn in the future, we will stop collection of such data but continue to store the data (save for Aadhaar data) and use it for internal purposes to further improve our services.<br/><br/>
In our efforts to continually improve our product and service offerings, we collect and analyse demographic and profile data about our users' activity on our Website.<br/><br/>
We identify and use your IP address to help diagnose problems with our server, and to administer our Website. Your IP address is also used to help identify you and to gather broad demographic information.<br/><br/>
We will occasionally ask you to complete optional online surveys. These surveys may ask you for contact information and demographic information (like zip code, age, or income level). We use this data to tailor your experience at our Website, providing you with content that we think you might be interested in and to display content according to your preferences.
.<br/><br/>

<strong>3.3.</strong>	Information collected in accordance with Clause 2 above, will not be sold to any third parties. Except as explicitly stated at the time of requesting such information, we do not disclose such information that you may have provided to us. Details of information that may be disclosed to third parties is provided for in Clause 4 below.<br/><br/>

<strong>4.	Disclosure of Personal Information</strong><br/><br/>

<strong>4.1.</strong>	All financial information that is collected through the Website is used solely to bill for the purchases made by the User on the Website, and is not used for marketing or promotional purposes. Towards this end, we may disclose such information to a third-party intermediary, for the sole purpose of credit card/debit card processing, which is used make payments by the User.<br/><br/>

<strong>4.2.</strong>	We may also disclose certain information to third parties solely to help diagnose technical problems, to administer the Website, and improve the quality of the Services provided by us.<br/><br/>

<strong>4.3.</strong>	We reserve the right to disclose any personal information as required by law and when we believe, at our sole discretion that disclosure is necessary to protect our rights, protect someone from injury and/or to comply with a judicial proceeding, court order, or legal process served on our Website.<br/><br/>

<strong>5.	Cookies</strong><br/><br/>

<strong>5.1.</strong>	The Website uses temporary cookies, which are files that your web browser puts on your system when you visit a website, to store certain information that is not sensitive personal information. The information collected through these cookies is used by us for the technical administration of the Website, research and development, and to improve the quality of our services.<br/><br/>

<strong>5.2.</strong>	We may use third party cookies to track visitor behaviour and to improve the quality of our services and communicate offers and promos based on your previous purchases and behaviour. However, such cookies will not store any kind of personal information, nor will such information be disclosed to any third party.<br/><br/>

<strong>5.3.</strong>	These cookies are intended to be automatically cleared or deleted when the User quits the browser application. You are encouraged to use the "clear cookies" functionality of your browser to ensure such clearing / deletion, since it is impossible for us to guarantee, predict or provide for the behaviour of your system.<br/><br/>

<strong>5.4.</strong>	The information we collect with cookies is not sold, rented or shared with any third parties.<br/><br/>


<strong>6.	Third Party links</strong><br/><br/>

We may provide links to third party websites for the convenience and information of Users. These websites may not be owned, controlled, or operated by us. In those cases, we cannot control how information collected by those websites will be used, shared, or secured. If the User visits linked sites, we strongly recommend that the User reviews the privacy notices or policies and terms of service posted at those sites. We are not responsible for the content of linked sites, the User's use of them, or the information practices of their operators.<br/><br/>

<strong>7.	Security Procedures</strong><br/><br/>

We have implemented industry standard security policies, rules and technical measures as required under Section 8 of the SPI rules, to protect any kind of personal sensitive information that we have under our control from unauthorized access, improper use or disclosure, unauthorized modification and unlawful destruction or accidental loss.<br/><br/>

<strong>8.	Retention on Information</strong><br/><br/>

We retain any personal information that you may have provided to us, for as long as you engaged our services, and for areasonable time thereafter. Upon request, we will provide you with a copy of your personal information which we keep with us, after providing us with proof of your identity.<br/><br/>

<strong>9.	Grievances</strong><br/><br/>

If you have any grievances as to the usage of any of your personal information or any other privacy concerns, you can contact the Grievance Officer whose details are provided in the Terms of Use, who will redress any such grievance that you might have within a period of 7 days.<br/><br/>

<strong>10.	Governing Law and Jurisdiction</strong><br/><br/>

The Privacy Policy shall be governed by and constructed in accordance with the applicable laws of India without reference to conflict of laws principles. Courts in Mysore, India shall have the exclusive jurisdiction to determine any disputes arising in relation to, or under, this Privacy Policy.<br/><br/></p>



        </div>
        </div>
<Footer/>
        </>
    )
}

export default Privacy;