import React,{useEffect} from 'react'
import './CommonContainer.css';
import Header from '../Component/Header/Header';

import Footer from '../Component/Footer/Footer';



const Terms = () => {


    return(
        <>
        <Header />
        <div className="container-fluid">
    
            <div className="row">
        <div className="brandcategorybanner col-lg-10 col-md-12 col-sm-12 col-12 my-2">
        <p><strong>TERMS OF USE</strong>-<a href="#">www.pickupinstore.com</a></p>
<p>
<strong>1.</strong>	Background</p>
<p>
<strong>1.1.</strong>	This document is an electronic record in terms of (i) Information Technology Act, 2000; (ii) the rules framed there under as applicable; and (iii) the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
  
  <p> <strong>1.2.</strong>	This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of<a href="#"> www.cityonnet.com</a> and the associated mobile application,which are collectively referred to as the <strong>"Website"</strong>.</p>

  <p><strong>1.3.</strong>	The Website is owned, registered and operated by Cityonthenet Marketplace Services Private Limited, ("Cityonthenet&#8482"), a private limited company, incorporated under the provisions of the Companies Act, 2013 and having its registered office at No.108, ShenoySadan, 2nd Floor, 3rd Cross, 9th Main, Saraswathipuram, Mysore-570009.</p>
   <p> <strong>1.4.</strong>	These terms of usage ("Terms of Use") govern Your use of the Website and Services (as defined below) provided through the Website. By using or visiting the Website, or by using any content or information provided as part of the Website/Services, You shall be deemed to have read, understood and accepted to be bound by these Terms of Use.</p>  
   <p><strong>1.5.</strong>	For the purpose of these Terms of Use, wherever the context so requires <strong>"You"</strong>, <strong>"Your"</strong> or <strong>"User"</strong> shall mean any natural or legal person who uses the Website for availing the Services. The term <strong>"We"</strong>, <strong>"Us"</strong>, <strong>"Our"</strong> shall mean Cityonthenet&#8482.</p>
   <p><strong>1.6.</strong>	We reserve the right to make changes to these Terms of Use at any time. Any such modifications will become effective immediately upon posting to the Website and Your continued use of the Website, and/or the Services constitutes Your agreement to such modifications. You agree to periodically review the current version of these Terms of Use as posted on the Website.</p>
   <p><strong>1.7.</strong>Multilingual Site:The translation that appear in different Indian languages are done with the Google Translator widget and is provided to users to give an indication of the name. we do not claim that it is accurate. Users discretion is advised.</p>
   <p><strong>2.	Services</strong></p>
   <p><strong>2.1.</strong>	Cityonthenet&#8482 through its Website provides a platform for the Users to reach a larger base of retailers to buy products or services offered by such retailers who have registered on to the Website. Further, Cityonthenet&#8482 through its Website offers an offline shopping feature (<strong>"Pick up in Shop&#8482"</strong>,<strong> "Pay at Store&#8482"</strong> and <strong>"Touch Feel and Buy&#8482"</strong>) whereby retailers market and advertise their products to the User on their respective webpage. This offline shopping feature provides the User with an option to visit the physical store of the retailer and collect the products ordered by such User on the retailer webpage
   </p>
   <p><strong>2.2.</strong>	It should be duly noted that Cityonthenet&#8482 is only providing a platform for communication between the Users and the retailers and it is agreed that the contract for sale of any of the products or services shall be a contract between the retailer and the User and both the parties shall be bound by the terms and conditions as specified in such contract(s).At no time shall Cityonthenet&#8482 hold any right, title or interest over the products nor shall Cityonthenet&#8482 have any obligations or liabilities in respect of such contract.</p>
   <p><strong>3.	Intellectual Property Rights</strong></p>
   <p><strong>3.1.</strong>	Copyright</p>
   <p><strong>3.1.1.</strong>	All content included on the Website and delivered to users as part of the Service, including but not limited to, text, graphics, logos, designs, photographs, button icons, images, data compilations, is the property of Cityonthenet&#8482, and is protected by the applicable intellectual property laws. The compilation of all content on this Website is the exclusive property of Cityonthenet&#8482, and shall not be reproduced or used without express written permission from Cityonthenet&#8482. You agree not to decompile, reverse engineer or disassemble any content accessible through the Website, not to insert any code or product or manipulate the content of the Website in any way that affects the user's experience, and not to use any data mining, data gathering or extraction method. We reserve the right to terminate our engagement if We, in our sole and absolute discretion, believe that You are in violation of this clause.</p>
   <p><strong>3.1.2.</strong>	Cityonthenet&#8482's content available on or via the Website, are provided to You AS IS for Your information and personal use only and may not be used, copied, reproduced, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited for any other purposes whatsoever without the prior written consent of Cityonthenet&#8482. Cityonthenet&#8482 reserves all rights, not expressly granted in and to the Website.</p>
   <p><strong>3.2.</strong>	Trademarks</p>
   <p><a href="#">www.cityonnet.com</a> is the domain of Cityonthenet&#8482. The Website, including, but not limited to its graphics, logos, page headers, button icons, scripts and service names constitute trade dress of Cityonthenet&#8482. The trademarks, domain names and trade dress of Cityonthenet&#8482 shall not be used or reproduced without prior written approval from Cityonthenet&#8482, and may not be used in connection with any product or service that is not affiliated with Cityonthenet&#8482, in any manner that is likely to (a) cause confusion among Users or potential users; or (b) dilute the rights of Cityonthenet&#8482, or (c) to disparage or discredit Cityonthenet&#8482.</p>
   <p><strong>3.3.</strong>	License and warranty for Your submission to the Website</p>
   <p>  <strong>3.3.1.</strong>	As between You and Cityonthenet&#8482, You own the Content and information You provide to Cityonthenet&#8482, and You may request its deletion at any time. Additionally, You grant Cityonthenet&#8482 a nonexclusive, irrevocable, worldwide, perpetual, unlimited, assignable, sub-licensable, fully paid up and royalty-free right to copy, prepare derivative works of, improve, distribute, publish, remove, retain, add, process, analyse, use and commercialize, in any way now known or in the future discovered, any information you provide, directly or indirectly to Cityonthenet&#8482, including, but not limited to, any user generated content, ideas, concepts, techniques and/or data to the services, You submit to Cityonthenet&#8482, without any further consent, notice and/or compensation to You or to any third parties.</p>
   <p><strong>3.3.2.</strong>	Pursuant to this license, Cityonthenet&#8482 may grant other users access and share rights to Your Content and information in accordance with these Terms of Use.</p>
   <p><strong>3.3.3.</strong>	Any Content or information You submit to Us is at Your own risk. By providing Content or information to Us, You represent and warrant that You are entitled to submit it and that it is not confidential and not in violation of any law, contractual restrictions or other third party rights (including any intellectual property rights).</p>
   <p><strong>3.3.4.</strong>	For the purpose of this clause, "Content" shall mean text, images, photos, location data, and all other forms of data or communication that You submit or transmit through, or in connection with the Website, such as ratings, reviews, invitations, messages, and information that You publicly display or displayed in Your account profile.</p>
   <p><strong>4.	User Account</strong></p>
   <p><strong>4.1.</strong>	In order to access or use the Website, you must be 18 (eighteen) years or older and have the requisite power and authority to enter into these Terms of Use. You may not access or use the Website if we have previously banned you from the Website or closed your account.</p>
   <p>
  <strong>4.2.</strong>	You may create an account and provide certain information about yourself in order to use the features that are offered by Cityonthenet&#8482 through the Website. You shall be responsible for maintaining the confidentiality of your username account password and You shall be responsible for any and all activities that occur in connection with your account.</p>
  <p>
  <strong>4.3.</strong>	Youagree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Website and refuse to provide You with access to the Website.</p>
  <p>  <strong>4.4.</strong>	While creating Your account, You agree to provide complete and accurate information about yourself to bolster your credibility as a contributor to the Website. You may not impersonate any third party to create or use an account for anyone other than yourself, provide an email address other than Your own, or create multiple accounts.</p>
  <p>
  <strong>5.	Fraud and Improper Conduct</strong>
  </p>
  <p><strong>5.1.</strong>	You may only access the Website and use the Services for lawful purposes. You are solely responsible for the knowledge of and adherence to any and all laws, rules, and regulations pertaining to Your use of the Services. You agree that You will not in any way:</p>
<p>(a)	interfere with the ability of others to access or use the Services;\n \n 
(b)	disrupt the normal flow of communication or otherwise act in a manner that adversely affects other users' ability to use the Website or the Services;
<br/><br/>
(c)	claim a relationship with or to speak for any individual, business, association, institution, or other organization for which You are not authorized to claim such a relationship;
<br/><br/>
(d)	interfere with or disrupt the Services or servers or networks connected to the Services, or disobey any requirements, procedures, policies, or regulations of networks connected to the Services;
<br/><br/>
(e)	upload or post or use the Service to transfer, any content or other material that contains or constitutes viruses, Trojan or other code with malicious, disruptive and/or destructive features;
<br/><br/>
(f)	 You shall not attempt to gain unauthorized access to any hardware or software systems or networks associated with the Service, or obtain any services or information not intentionally made available to You by Cityonthenet&#8482 on or through the Service;<br/><br/>

(g)	You shall not attempt to gain unauthorized access to the Account of any other user or entity, or otherwise interfere with any other user's or entity's use of the Service;
<br/><br/>
(h)	You shall not use any false or misleading information (e.g., false or misleading names, email addresses or URLs) when using the Service, including, without limitation, with respect to any identifying information for Your account, and all information that You provide must be accurate and correct, and You must update any changes to such information, so that it remains current.<br/><br/>
 </p> 


 <p class="ter"><strong>6.	Limitation and Disclaimer of Warranty</strong><br/><br/>

<strong>6.1.</strong>	The Website, the Services and each portion thereof are provided "as is" without warranties of any kind either express or implied. To the fullest extent possible pursuant to applicable laws of India, We disclaim all warranties, express or implied, with respect to the Website, the Services and each portion thereof, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or other violation of rights.<br/><br/>

<strong>6.2.</strong>	Cityonthenet&#8482 does not warrant or make any representations regarding the use, validity, accuracy, or reliability of, or the results of the use of, or otherwise with respect to, the Website or its Services.<br/><br/>

<strong>6.3.</strong>	Under no circumstances, including, but not limited to, negligence, shall Cityonthenet&#8482 be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the Website, the Services or any portion thereof, by any person, including employees and contracted personnel of Cityonthenet&#8482.<br/><br/>

<strong>6.4.</strong>	Under no circumstances, shall Cityonthenet&#8482 be liable for any direct, indirect, special, incidental or consequential loss or damages arising due to gross negligence or wilful misconduct of any third party service providers (payment gateway service provider(s), logistics service provider(s)) empanelled by Cityonthenet&#8482 to enable effective processing of transaction between the retailer and the User.<br/><br/>  

<strong>6.5.</strong>	You acknowledge that Cityonthenet&#8482 is only an aggregator of retailers on the Website. You further agree that neither Cityonthenet&#8482 nor its directors, officers, agents, servants and employees shall be liable for disputes arising between You and the retailers and You agree to release Us from any claims, demands, and damages (actual and consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with the retailer or any third-party.<br/><br/>

<strong>6.6.</strong>	You are advised that any offer made by the retailer on his/her/its products on any media platform (excluding the Website) including but not limited to flyers, magazines and newspapers may or may not be applicable on the same products displayed on the Website.<br/><br/>

<strong>6.7.</strong>	If You are dissatisfied or harmed by this Website or anything related the Website, You may terminate these Terms of Use in accordance with Clause 9below and such termination shall be Your sole and exclusive remedy.<br/><br/>

<strong>6.8.</strong>	Cityonthenet&#8482 does not guarantee that the Services it provides will function without interruption or errors in functioning. In particular, the operation of Services may be interrupted due to maintenance updates, or system or network failures. In the event of interruption in provision of the Services due to the above mentioned reasons, Cityonthenet&#8482 shall inform the User of the same, and Cityonthenet&#8482 disclaims all liability with respect to delay in provision of Services due to the same.<br/><br/>


<strong>7.	Obligations of the User </strong><br/><br/>

<strong>7.1.</strong>	In the event You avail the offline shopping feature offered by Cityonthenet&#8482 through its Website, You shall be required to claim Your order from the physical store of the retailer within three days of placing such order. Similarly, in the event, You reserve a product using the offline or online shopping feature, You shall be required to claim such products within the reservation period agreed by the retailer. Failure to do so shall entitle the retailer to offer such products for sale or sell the same to any other customer with/without issuing a prior notice to You.<br/><br/>

<strong>7.2.</strong>	In the event You opt for a Cash on Delivery (COD)/ Demand Drafton Delivery (DOD) transaction, You shall ensure that You or any other person accepting the order on Your behalfpay the requisite amount as specified in the invoice issued by the retailer. In order to facilitate payments through credit-cards/debit-cards, Cityonthenet&#8482 shall provide mPOS* machines through the delivery personnel to make such payments.<br/><br/> 

*Please note that the facility to use mPOS machines is restricted to certain specific areas as notified by Cityonthenet&#8482 on the Website from time to time.<br/><br/> 

<strong>7.3.</strong>	Under no circumstances shall the User make payments against his/her invoice partially through cash and partially through card (debit card/credit card) or partially through online transfer and partially through cash/card (debit card/credit card).<br/><br/>

<strong>7.4.</strong>	In the event of a failed transaction wherein the money is debited from Your account but thesame has not been credited to the retailer's account, You may provide Cityonthenet&#8482 with the relevant transaction documents to validate such a transaction, following which, Cityonthenet&#8482 shall take necessary steps to track such transaction and refund the requisite amount or process the order accordingly. <br/><br/>

<strong>7.5.</strong>	In the event You intend to return or exchange products purchased through the Website, You may do so in accordance with the terms and conditions outlined by the retailer on his/her/its webpage. In the event You wish to return/exchange a product purchased through the offline shopping feature made available through the Website, You may do so by visiting the Retailer's store from where the product was originally purchased.<br/><br/>

<strong>7.6.</strong>	It shall be Your sole responsibility to redeem any offers made by the retailer within the redemption period specified by the retailer while making such offer or before the expiry of such products on which the offer made by the retailer is applicable.<br/><br/>

<strong>7.7.</strong>	You shall not transfer Your account to any other User without obtaining a prior written consent from Cityonthenet&#8482.<br/><br/>

<strong>7.8.</strong>	You may make your payments against the invoice issued by the retailer through (i) Online payment; (ii) Cash on Delivery/Demand draft on Delivery or via your credit card/debit card (specific areas ONLY); and (iii) Offline payment i.e., payment of the invoice amount upon collecting the order from the retailers store. Please note that retailers may not provide COD/DOD transaction in certain specific areas due to safety concerns. Such areas shall be mentioned by the Retailer on their respective webpage.<br/><br/>

<strong>7.9.</strong>	In the event a feedback, a comment or any communication made by the User on the Website contain profanity or abusive language, Cityonthenet&#8482 shall have the right to take disciplinary action against such User which may result in indefinite suspension of the User's account, temporary suspension of the User's account or issue a formal warning to such User.<br/><br/>

<strong>7.10.</strong>	You shall not be permitted to make bulk orders of products beyond the limitation specified by the retailer on his/her/its Webpage. In the event it comes to the notice of Cityonthenet&#8482 that You are using the Website for your personal or commercial benefit, Cityonthenet&#8482 may permanently suspend your account. <br/><br/>

<strong>8.	Indemnification</strong><br/><br/>

You agree to indemnify, defend and hold harmless Cityonthenet&#8482, and our affiliates, officers, directors, agents, partners, employees and representatives, from and against all losses, expenses, damages, costs, claims and demands, including reasonable attorney's fees and related costs and expenses, due to or arising out of, (a) Your failure to comply with these Terms of Use; or (b) where any content You submit, email, or otherwise transmit to Us violates third party rights or applicable laws; or (c) any content You submit through Your use of the Services, or any portion thereof, Your connection to the Services that violates third party rights or applicable laws. We reserve the right, at our own expense, to assume the exclusive defence and control of any matter otherwise subject to indemnification by You, and in such case, You agree to fully cooperate with such defence and in asserting any available defences.<br/><br/>

<strong>9.	Termination</strong><br/><br/>

<strong>9.1.</strong>	Cityonthenet&#8482 may terminate these Terms of Use immediately without notice in the event of any breach by You of these Terms of Use or any of our applicable policies, as posted on the Website from time to time or upon a misuse of the Services by You.<br/><br/>

<strong>9.2.</strong>	You may terminate these Terms of Use, for any or no reason, at any time, with notice to Cityonthenet&#8482 pursuant to this Clause 9.2. This notice will be effective upon Cityonthenet&#8482 processing Your notice.<br/><br/>

<strong>9.3.</strong>	In the event of any termination or expiration of these Terms of Use, the following sections of these Terms of Use shall survive: all provisions regarding ownership of intellectual property, indemnification, disclaimer of warranties and limitations of liability, fraud or abuse, and the provisions of this section.<br/><br/>

<strong>9.4.</strong>	You agree that upon the termination of these Terms of Use, We may delete all information related to You with respect to the Services availed by You.<b/><br/>/

<strong>10.	Links</strong><br/><br/>

<strong>10.1.</strong>	The Website or the Services may contain links to content or other files belonging to other websites ("Linked Sites"). The Linked Sites are not under the control of the Website. We are not responsible for the content of any Linked Site, including, without limitation to, any link contained in a Linked Site, or any changes or updates to a Linked Site.<br/><br/>

<strong>10.2.</strong>	We are not responsible for any form of transmission, whatsoever, received by the User from any Linked Site. We are providing these links only as a convenience, and the inclusion of any suck link does not imply endorsement by the Website of the Linked Sites or any association with its operators or owners including the legal heirs or assigns thereof.<br/><br/>

<strong>10.3.</strong>	On accessing the Linked Sites, You shall be governed by the terms of use, privacy policy and such other additional policies of the Linked Sites. You further acknowledge and agree that We shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, advertising, products, services or other materials available on or through any Linked Sites or for any errors, defamatory content, libel, slander, omissions, falsehoods, obscene content, pornographic material, or any profanity contained therein.<br/><br/>


<strong>11.	Severability</strong><br/><br/>
    
If any part of the Terms of Use for Services are determined to be invalid or unenforceable pursuant to applicable laws of India, including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed to be superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the Terms of Use for Services shall continue in effect.<br/><br/>

<strong>12.	General</strong><br/><br/>

Unless otherwise specified herein, these Terms of Use for Services constitute the entire agreement between you and Cityonthenet&#8482 in respect of the Services and supersedes all previous written and oral agreements between you and Cityonthenet&#8482, if any. Cityonthenet&#8482's failure to act with respect to a breach by you or others does not waive its right to act with respect to subsequent or similar breaches.<br/><br/>

<strong>13.	Governing Law and Dispute Resolution</strong><br/><br/>

These Terms of Use shall be governed by and constructed in accordance with the applicable laws of India without reference to conflict of laws principles. The courts in Mysore, India shall have the exclusive jurisdiction to determine any disputes arising in relation to, or under, these Terms of Use.<br/><br/>

<strong>14.	Grievance Officer </strong><br/><br/>

In accordance with the Information Technology Act, 2000 and rules made there under, the name and contact details of the Grievance Officer are provided below:<br/><br/>


CityontheNet Marketplace Services Private Limited,<br/>
#108, Shenoy Sadan 2nd Floor<br/> 
9th Main , 3rd Cross,<br/>
Saraswathipuram,<br/>
Mysuru - 570009<br/>
Phone: 0821-4266909 / 7259922200<br/>
Email: info@cityonnet<br/>
Time: Mon - Sat (9:00 - 18:00)<br/><br/><br/>









 






    
    
    
    
    
    
    
    
    
</p>
<p class="ter">
<strong>Important : </strong> You expressly acknowledge CityontheNet shall not in any manner be held liable  as CityontheNet is only the facilitator between You and the Seller. <br/><br/>

<strong>Cancellation Policy :</strong>
There may be certain orders that CityontheNet’s Merchant partners are unable to accept and service and these may need to be cancelled. Some situations that may result in your order being cancelled include, non-availability of the product or quantities ordered by you, non- availability of the delivery service in the address to which product is required to be shipped, inaccuracies or errors in pricing information specified by our Merchant partners, or problems identified by CityontheNet’s credit and fraud avoidance department. CityontheNet may also require additional verifications or information before accepting any order. CityontheNet will inform you if all or any portion of your order is cancelled or if additional information is required to accept your order. If your order is cancelled after your credit card or bank account has been charged, the said amount will be re-deposited to your credit card / bank account.  <br/><br/>
 
 
<strong>Cancellation by the User :</strong>
Conveniently place your return request online if you've received an item in a 'Damaged', 'Defective' or 'Not as Described' state. <br/><br/>
 Cancellation of products can be done within 24 hours by the user.
 In case of requests for order cancellations, Seller reserves the right to accept or reject requests for order cancellations for any reason whatsoever. As part of usual business practice, if Seller receives a cancellation notice and the order has not been processed/ approved by Seller, Seller shall cancel the order and refund the entire amount or refund the amount deducting the bank charges from Customer which is decided by the Seller subject to cancellation. Seller will not be able to cancel orders that have already been processed. Seller has the full right to decide whether an order has been processed or not. You agree not to dispute the decision made by Seller or CityontheNet and accept Seller’s or CityontheNet’s decision regarding the cancellation. In cases where it is not possible to cancel orders since they have already been shipped, refund shall be made subject to the returns process post return request is raised and you would get replacement or refund once the original item is back with the Seller in good sale-able condition.<br/>
 Seller reserves the right to cancel any orders that classify as ‘Bulk Order’ as determined by CityontheNet or Seller as per certain criteria. An order can be classified as ‘Bulk Order’ if it meets with the below mentioned criteria, which may not be exhaustive, viz:<br/>
</p>


<p class="spa">(a) Bulk quantity of the same product ordered<br/><br/>

(b) Products ordered are not for self-consumption but for commercial resale<br/><br/>
(c) Multiple orders placed for same product at the same address<br/><br/>

(d) Any malpractice used to place the order<br/><br/>

</p>  
<strong>Return Policy </strong><br/><br/>
  <p class="spa">(a) In the event you receive a damaged / defective product or a product that does not comply with the specifications as per your original order, you are required to get in touch with the Seller.<br/><br/>

  (b) Returns are subject to the Seller's return policy which was there in the product page, where you can see the respective policy against each Seller offering that product.<br/><br/>

  (c) Upon receiving your complaint, Seller shall verify the authenticity and the nature of the complaint. If addressed to CityontheNet and CityontheNet is  convinced that the complaint is genuine, CityontheNet will inform the relevant Seller of such complaint and request for a replacement. However, in the event of frivolous and unjustified complaints regarding the quality and content of the products, Seller and/or CityontheNet reserves the right to pursue necessary legal actions against you and you will be solely liable for all costs incurred by CityontheNet and/or Seller in this regard. You expressly acknowledge that the Seller selling the defective product/ service will be solely responsible to you for any claims that you may have in relation to such defective product/ service and CityontheNet shall not in any manner be held liable for the same.<br/><br/>
  (d) Before accepting shipment of any product, kindly ensure that the product’s packaging is not damaged or tampered. If you observe that the package is damaged or tampered, request you to refuse to accept delivery and inform Seller and CityontheNet at the earliest. The return process of the product may be restricted by Seller depending on the nature and category of the product.<br/><br/>

  (e) In order to return any products sold through the Website, you are required to comply with the below mentioned conditions, viz:<br/>

  <p class="tercan">
  I.	For non-damaged/ non defective product/service, you shall be allowed to return the product within the time frame displayed on website at the time of purchase.<br/><br/>
  II.	Please notify Seller of receipt of a damaged/ defective product/service within 48-hours of delivery to you. If you are unable to do so within 48-hours, CityontheNet/Seller/manufacturer/service provider shall not be held liable for the failure to replace the order;<br/><br/>
  III.	If it ’is a local delivery you have return the products back to Seller. Seller will arrange pick-up of the damaged/defective product through 3rd party logistics partner. In the event Seller is unable to do so, Seller will notify you regarding the same and you will be required to dispatch the product using a reputed courier in your respective area within one (1) day from receipt of such notice. Courier freight charges will be reimbursed in such form as is determined by the logistics team upon prior consultation with Seller or you have to bear the shipping charges subject to the return process;<br/><br/>
  IV.	Products should be returned in their original packaging along with the original price tags, labels, barcodes, user manual, warranty card and invoices etc.;<br/><br/>
  V.	It is advised that the return packets should be strongly and adequately packaged so that there is no further damage of products during transit;<br/><br/>
  VI.	The returned products are subject to verification and checks by Seller in order to determine the legitimacy of the complaint/ return.<br/><br/>
  VII.	In the event the return of a product is duly accepted by Seller, the value of such product, as originally paid by you during acceptance of delivery of product or otherwise, will be refunded to you. Refund will be processed based on the mode of payment and Seller will credit your the refunds to your account. Refunds will be subject to the following:<br/>


  <p class="tercanplo">
  a.	Orders paid online will be refunded to your bank account<br/>
  b.	For Cash on Delivery payments also the amount will be refunded into your bank account and you have to provide the bank account details.<br/>
  c.	It will take 3-21 days for the money to show reflect in your bank account depending on your Bank’s policy..
  </p>
  </p> 
  </p>  </div>

        </div>
        </div>
<Footer/>
        </>
    )
}

export default Terms;